webapp:
  index: redirect:/swagger-ui.html
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      properties:
#        hibernate:
#          temp:
#            use_jdbc_metadata_defaults: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/intelligent_system?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 649721
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
